### ISSUE TITLE
[BUG] Wurst+3 randomly crashes

### ISSUE THREAD

**Issue by chocopie69** [WurstPlus/wurst-plus-three#216]
**Describe the bug**
sometimes w+3 crashes for no reason, it happens even more if I use w+3 with other clients

**To Reproduce**
1. open w+3
2. play for a few minutes
3. crashes

**Expected behavior**
it shouldn't crash

It also happens with other people aswell
Logs are useless because each time it crashes its a different issue in logs

**Comment by chocopie69** [comment]
Example logs:
```
[11:39:48] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown!
java.lang.NullPointerException: null
	at net.minecraft.client.renderer.EntityRenderer.func_78473_a(EntityRenderer.java:522) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1597) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[11:39:48] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:unload:3910]: unloading wurst+3
[11:39:48] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:unload:3912]: wurst+3 has been unloaded
[11:39:48] [Client thread/INFO] [net.minecraft.client.Minecraft]: Stopping!
[11:39:49] [Client thread/INFO] [net.minecraft.client.audio.SoundManager]: SoundSystem shutting down...
[11:39:49] [Client thread/WARN] [net.minecraft.client.audio.SoundManager]: Author: Paul Lamb, www.paulscode.com
```

**Comment by wallhacks0** [comment]
This is a known issue with a non known fix thx for reporting tho
